name: ci

on:
  pull_request:
    types: [opened, synchronize, ready_for_review]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        shell: bash
        run: npm ci

      - name: Lint
        shell: bash
        run: npm run lint
