name: publish

on:
  release:
    types: [published]
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Login to npm
        shell: bash
        run: npm set "//registry.npmjs.org/:_authToken" ${{ secrets.NPM_TOKEN }}

      - name: Install dependencies
        shell: bash
        run: npm ci

      - name: Publish package
        shell: bash
        run: npm run release $NPM_PACKAGE_VERSION -- --tag=$NPM_PACKAGE_TAG --no-tests
        env:
          NPM_PACKAGE_VERSION: ${{ github.event_name == 'release' && github.event.release || 'prerelease' }}
          NPM_PACKAGE_TAG: ${{ github.event_name == 'release' && 'latest' || 'next' }}
