name: publish

on:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        shell: bash
        run: npm ci

      - name: Publish package
        shell: bash
        run: npm run release $NPM_PACKAGE_VERSION -- --tag=$NPM_PACKAGE_TAG
        env:
          NPM_PACKAGE_VERSION: ${{ github.event_name == 'push' && 'prerelease' || github.event.release.tag_name }}
          NPM_PACKAGE_TAG: ${{ github.event_name == 'push' && 'next' || 'latest' }}
