name: publish

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        shell: bash
        run: npm ci

      - name: Prepare npm config for publish
        shell: bash
        run: echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' >> .npmrc

      - name: Publish package
        shell: bash
        run: |
          npm run release $NPM_PACKAGE_VERSION -- --tag=$NPM_PACKAGE_TAG --no-tests --message "chore: v%s"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_PACKAGE_VERSION: ${{ github.event_name == 'release' && github.event.release || 'prerelease' }}
          NPM_PACKAGE_TAG: ${{ github.event_name == 'release' && 'latest' || 'next' }}
