name: publish

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: Version to publish
        default: prerelease
        required: true
      tag:
        type: choice
        description: Tag to publish
        default: next
        options:
          - latest
          - next
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Login to npm
        shell: bash
        run: npm set "//registry.npmjs.org/:_authToken" ${{ secrets.NPM_TOKEN }}

      - name: Install dependencies
        shell: bash
        run: npm ci

      - name: Publish package
        shell: bash
        run: npm run release ${{ github.event.inputs.version }} -- --tag=${{ github.event.inputs.tag }}
