name: semantic

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  semantic:
    runs-on: ubuntu-latest

    steps:
      - name: Check pull request
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
